### ISSUE TITLE
modify cando.sh to allow pop-os users to install cando

### ISSUE THREAD

**Issue by dacase** [cando-developers/cando#61]
System76.com provides an Ubuntu varant, pop-os, which has some nice additions to Ubuntu (in the user interface area) and comes with their machines.

If one adds a option in cando.sh in the `case "{ID-}" in` loop like this:
```
  pop)
    ubuntu ;;
```
then pop-os users can install the nightly builds.

Works for me, and seems(?) pretty safe: pop-os is just some lipstick on top of Ubuntu itself, and you might get a few more users.

...thx...dac

**Comment by yitzchak** [comment]
Done. [ab5b1a031915b5cf8891fbd64cae0c95b2529efe](https://github.com/clasp-developers/clasp/commit/ab5b1a031915b5cf8891fbd64cae0c95b2529efe)

Should be tomorrows build.
